### PR TITLE
Update CI.yml

### LINKED ISSUE #7: automatic documentation deployment broken
due to un-registered dependency `MultipliableDimArrays.jl`

see branch initialize-docs

### PR DESCRIPTION
**Pull request by briochemc**
fix #7 

I'm not entirely sure but something like that would be the way I'd deal with unregistered deps in CI.

### CODE REVIEW

**Comment by ggebbie** [comment]
good ideas

In other work, I tried adding a explicit Manifest.toml to the the docs environment. Could you try this?

**Comment by ggebbie** [comment]
previously I solved the unsatisfiable requirements issue with an unregistered package this way: https://github.com/ggebbie/TMItransient.jl/issues/28#issuecomment-2353386179

**Comment by briochemc** [comment]
> good ideas
> 
> In other work, I tried adding a explicit Manifest.toml to the the docs environment. Could you try this?

I don't think this is necessary. The issue was I think (i) not adding the unregistered dep manually (with its URL), and (ii) having OceanGreensFunctionMethods as a dep of its own docs.

**Comment by briochemc** [comment]
Do you want me to revert the change of the project version number so it's back to 1.0.13-DEV?

**Review by ggebbie — APPROVED** [review]

**Comment by ggebbie** [comment]
this is really nifty!  a long-term outstanding issue has been handled

Thanks a lot!

Will wait for version number to go back to DEV for consistency and then merge

**Pull request merged**
